### ISSUE TITLE
 s2protocol.decoders.CorruptedError: buffer(00/0,[1]=22)

### ISSUE THREAD

**Issue by StanczakDominik** [SC2GoalTracker/SC2GoalTracker#14]
Trying to run this on Linux (might be a stretch, of course, but I'd like to see if I can get this working here) with Python 3:

```python
09:48:38 dominik: ~/Code/github/SC2GoalTracker/SC2GoalTracker $ python sc2_goal_tracker.py 
[INFO   ] [Logger      ] Record log in /home/dominik/.kivy/logs/kivy_19-02-24_15.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[WARNING] The 'fake' fullscreen option has been deprecated, use Window.borderless or the borderless Config option instead.
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 18.3.3'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "sc2_goal_tracker.py", line 168, in <module>
     test = TestApp().run()
   File "/usr/lib/python3.7/site-packages/kivy/app.py", line 800, in run
     root = self.build()
   File "sc2_goal_tracker.py", line 31, in build
     self.replay_stats = replay_stats(self.main_race,self.main_race_only,self.replay_analyze.get_already_played(),self.today_goal,self.week_goal)
   File "/home/dominik/Code/github/SC2GoalTracker/SC2GoalTracker/replay_analyzer.py", line 120, in get_already_played
     header = versions.latest().decode_replay_header(contents)
   File "/home/dominik/.local/lib/python3.7/site-packages/s2protocol/versions/protocol72282.py", line 475, in decode_replay_header
     return decoder.instance(replay_header_typeid)
   File "/home/dominik/.local/lib/python3.7/site-packages/s2protocol/decoders.py", line 181, in instance
     return getattr(self, typeinfo[0])(*typeinfo[1])
   File "/home/dominik/.local/lib/python3.7/site-packages/s2protocol/decoders.py", line 260, in _struct
     self._expect_skip(5)
   File "/home/dominik/.local/lib/python3.7/site-packages/s2protocol/decoders.py", line 194, in _expect_skip
     raise CorruptedError(self)
 s2protocol.decoders.CorruptedError: buffer(00/0,[1]=22)
```

It seems the error occurs in this part:
```python
    115             if (path.splitext(files)[1] == '.SC2Replay'):
    116                 archive = mpyq.MPQArchive(path.join(self.replay_folder, files))
    117                 contents = str(archive.header['user_data_header']['content'])
    118 
    119                 #figure out build version of replay
--> 120                 header = versions.latest().decode_replay_header(contents)
    121                 baseBuild = header['m_version']['m_baseBuild']
    122                 protocol = versions.build(baseBuild)
    123 
    124                 #decode game events
    125                 contents = archive.read_file('replay.details')
ipdb> p contents                                                                                                                                                                              
'b"\\x05\\x12\\x00\\x02,StarCraft II replay\\x1b11\\x02\\x05\\x0c\\x00\\t\\x02\\x02\\t\\x08\\x04\\t\\x10\\x06\\t\\x04\\x08\\t\\xde\\xdf\\x08\\n\\t\\xde\\xdf\\x08\\x04\\t\\x04\\x06\\t\\xbc\\x9a\\x01\\x08\\x06\\x01\\n\\x05\\x02\\x02\\x02 \\xfe\\x90\\xc9\'\\x16\\xfco\\x8f\\x04\\xb7Bh\\xec6\\x9f\\xa5\\x0c\\t\\xde\\xdf\\x08\\x0e\\x05\\x02\\x02\\x02 \\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x10\\x06\\x00"'
```

I'm suspecting some sort of a Python 2/3 compatibility mixup. Could you post what `contents` looks like for you? That'd help remove that bug!

**Comment by StanczakDominik** [comment]
Okay, apologies, this might be an upstream problem - I've managed to get this running on Py2.7 and this is my output there:
```python
ipdb> p versions.latest()
<module 'protocol72282' from '/home/dominik/.local/lib/python2.7/site-packages/s2protocol/versions/protocol72282.pyc'>
ipdb> p versions.latest().decode_replay_header(contents)
{'m_useScaledTime': True, 'm_version': {'m_baseBuild': 71663, 'm_minor': 8, 'm_revision': 2, 'm_flags': 1, 'm_major': 4, 'm_build': 71663}, 'm_type': 2, 'm_signature': 'StarCraft II replay\x1b11', 'm_ngdpRootKey': {'m_data': "\xfe\x90\xc9'\x16\xfco\x8f\x04\xb7Bh\xec6\x9f\xa5"}, 'm_elapsedGameLoops': 3408, 'm_ngdpRootKeyIsDevData': False, 'm_replayCompatibilityHash': {'m_data': '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}, 'm_dataBuildNum': 71663}
```
While for Py3.7:
```python
ipdb> p versions.latest()                                                                    
<module 'protocol72282' from '/home/dominik/.local/lib/python3.7/site-packages/s2protocol/versions/protocol72282.py'>
ipdb> p versions.latest().decode_replay_header(contents)                                     
*** s2protocol.decoders.CorruptedError: buffer(00/0,[1]=22)
```
So this is probably a `s2protocol` issue. My bad!

**Comment by StanczakDominik** [comment]
Actually this might be connected to #15 (mixing `bytes` and `str`s...)
